---
- name: set current host MAC address
  set_fact:
    pi_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

- name: set hostname and ip based on MAC address
  set_fact:
    pi_hostname: "{{ mac_address_mapping[pi_mac_address].name }}"
    pi_ip_address: "{{ mac_address_mapping[pi_mac_address].ip }}"

- name: set networking config files
  template:
    src: "templates/{{ item.template }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { template: hosts.j2, dest: /etc/hosts }
    - { template: hostname.j2, dest: /etc/hostname }
    - { template: resolv.conf.j2, dest: /etc/resolv.conf }
    - { template: 99_config.yaml.j2, dest: /etc/netplan/99_config.yaml }
  notify:
    - update hostname
    - delete dhcp leases
    - reboot server
  become: true
  become_user: root
