---
- name: restart crond
  systemd:
    name: crond 
    state: restarted
  become: true
  become_user: root

- name: restart sshd
  systemd:
    name: sshd 
    state: restarted
  become: true
  become_user: root

- name: restart systemd-journald
  systemd:
    name: systemd-journald
    state: restarted
  become: true
  become_user: root

- name: reboot server
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  become: true
  become_user: root
