---

- name: Create nginx user
  user:
    name: "{{ nginx_user }}"
    shell: /bin/bash
  become: true
  become_user: root

- name: Install nginx
  apt:
    name:
      - nginx
  become: true
  become_user: root

- name: Setup default nginx config file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_dir }}/nginx.conf"
  notify: reload nginx
  become: true
  become_user: root

- name: Setup nginx systemd file
  template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
  notify: restart nginx
  become: true
  become_user: root

- name: Enable nginx unit on startup
  systemd:
    name: nginx
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
