---

- name: update hostname
  command: "hostname {{ pi_hostname }}"
  become: true
  become_user: root

- name: delete dhcp leases
  file:
    path: /var/lib/dhcp/dhclient.leases
    state: absent
  with_items:
    - /var/lib/dhcp/dhclient.leases
    - /var/lib/dhcpcd5/dhcpcd-eth0.lease
  become: true
  become_user: root
