---

- name: Install system dependencies
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - virtualenv
    state: latest
    update_cache: true
  retries: 3
  become: true
  become_user: root

- name: create blinkstick user
  user:
    name: "{{ blinkstick_user }}"
    shell: /bin/bash
  become: true
  become_user: root

- name: Create application directories
  file:
    path: "{{ blinkstick_install_dir}}/app"
    state: directory
    owner: "{{ blinkstick_user }}"
    group: "{{ blinkstick_user }}"
    mode: "0700"
  become: true
  become_user: root

- name: Copy python applicatiion
  template:
    src: blinkstick_cpu.py.j2
    dest: "{{ blinkstick_install_dir }}/app/blinkstick_cpu.py"
  notify: restart blinkstick
  become: true
  become_user: root

- name: Install application dependencies
  pip:
    name:
      - blinkstick
      - psutil
    virtualenv: "{{ blinkstick_install_dir }}/venv"
    virtualenv_python: python3
  notify: restart blinkstick
  become: true
  become_user: root

- name: Setup stystemd
  template:
    src: blinkstick.service.j2
    dest: /etc/systemd/system/blinkstick.service
  notify: restart blinkstick
  become: true
  become_user: root

- name: Enable blinkstick systemd unit at startup
  systemd:
    name: blinkstick
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
