---
- name: create mosquitto group
  group:
    name: mosquitto
    state: present
  become: true

- name: create mosquitto user
  user:
    name: mosquitto
    group: mosquitto
    state: present
  become: true

- name: create mosquitto data directory
  file:
    path: "{{ mosquitto_data_dir }}"
    state: directory
    owner: mosquitto
    group: mosquitto
    mode: 0740
  become: true

- name: install apt_key dependencies
  apt:
    name: gpg
    state: present
  become: true

- name: Add an apt signing key
  apt_key:
    url: http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
    state: present
  become: true

- name: Install mosquitto repository
  apt_repository:
    repo: deb http://repo.mosquitto.org/debian/ buster main
    state: present
  become: true

- name: install mosquitto
  apt:
    name: mosquitto
    state: present
  become: true

- name: copy local  mosquitto config file
  template:
    src: custom.conf.j2
    dest: /etc/mosquitto/conf.d/custom.conf
  become: true
  notify:
    - reload mosquitto

- name: copy systemd service file.
  template:
    src: mosquitto.service.j2
    dest: /etc/systemd/system/mosquitto.service
  become: true
  become_user: root
  notify:
    - restart mosquitto

- name: ensure mosquitto service is started and enabled
  systemd:
    daemon_reload: true
    name: mosquitto
    state: started
    enabled: true
  become: true
  become_user: root
