---

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - python3-pip
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - docker-compose
    state: present
    update_cache: true
  become_user: root
  become: true

- name: Add Docker apt key.
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  become_user: root
  become: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    update_cache: true
  become_user: root
  become: true

- name: Install Docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present 
    update_cache: true
  notify: restart docker
  become_user: root
  become: true

- name: ensure docker service is started and enabled
  systemd:
    daemon_reload: true
    name: docker 
    state: started
    enabled: true
  become_user: root
  become: true
