---

- name: Install wireguard
  apt:
    name: wireguard
    state: present
  become: true

- name: Generate and register a wireguard private key
  shell: 'wg genkey'
  register: private_key

- name: Set the server private key fact
  set_fact:
    wireguard_server_private_key: "{{ private_key.stdout }}"

- name: Generate and register a wireguard public key from private key
  shell: 'wg pubkey'
  args:
    stdin: "{{ wireguard_server_private_key }}"
  register: public_key

- name: Set the server public key fact
  set_fact:
    wireguard_server_public_key: "{{ public_key.stdout }}"

- name: copy wg0.conf file
  template:
    src: wg0.conf.j2
    dest: "etc/wireguard/wg0.conf"
    owner: root
    group: root
    mode: 0600
  become_user: root
  become: true
