---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: true
  become_user: root

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: true
  become_user: root
