- name: setup the systemd service file.
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node exporter
  become: true
  become_user: root

- name: Ensure Node Exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  become: true
  become_user: root
