---

- name: check if the node exporter binary is installed.
  stat:
    path: "/usr/local/bin/node_exporter"
  register: node_exporter_is_installed

- name: if installed, register node expoprter version.
  command: "/usr/local/bin/node_exporter --version"
  changed_when: false
  register: node_exporter_version_output
  when: node_exporter_is_installed.stat.exists

- name: install or upgrade node exporter.
  import_tasks: install.yml
  when: (not node_exporter_is_installed.stat.exists) or (node_exporter_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version)

