---

- name: update hostname
  command: "hostname {{ pi_hostname }}"
  become: true
  become_user: root

- name: delete dhcp leases
  file:
    path: /var/lib/dhcp/dhclient.leases
    state: absent
  become: true
  become_user: root

- name: reboot server
  reboot:
    msg: Rebooting Host
    reboot_timeout: 3600
  become: true
  become_user: root

