---

- name: create prometheus group
  group:
    name: prometheus
    state: present
  become: true

- name: create prometheus user
  user:
    name: prometheus
    group: prometheus
    state: present
  become: true

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  become: true

- name: install and unarchive prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}-rc.0/prometheus-{{ prometheus_version }}-rc.0.linux-armv7.tar.gz
    dest: /tmp
    remote_src: yes
  retries: 5

- name: create prometheus systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: prometheus
    group: prometheus
    mode: 0644
  become: true
  beomce_user: root
  notify:
    - restart prometheus
