---

- name: create prometheus group
  group:
    name: prometheus
    state: present
  become: true

- name: create prometheus user
  user:
    name: prometheus
    group: prometheus
    state: present
  become: true

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  become: true
