---

- name: create prometheus group
  group:
    name: prometheus
    system: true
    state: present
  become_user: root
  become: true

- name: create prometheus user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    state: present
    createhome: false
  become_user: root
  become: true

- name: create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  become_user: root
  become: true

- name: create prometheus configuration directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root 
    group: prometheus
    mode: 0770
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
  become_user: root
  become: true

- name: install prometheus package
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ prometheus_arch}}.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
  retries: 5
  delay: 2
  become_user: root
  become: true

- name: unarchive prometheus package
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
    dest: /tmp
    creates: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/prometheus"
    remote_src: true
  become_user: root
  become: true

- name: copy prometheus and promtool binaries
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item }}"
    dest: "{{ prometheus_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    remote_src: true
  with_items:
    - prometheus
    - promtool
  become_user: root
  become: true
  notify:
    - restart prometheus

- name: copy official console templates
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0755
    owner: prometheus 
    group: prometheus 
    remote_src: true
  with_items:
    - console_libraries
    - consoles
  become_user: root
  become: true
  notify:
    - restart prometheus

- name: copy alert rules configuration file
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root 
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_install_dir }}/promtool check rules %s"
  become_user: root
  become: true
  notify:
    - reload prometheus

- name: configure prometheus 
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: root 
    group: prometheus
    mode: 0640
    validate: "{{ prometheus_install_dir }}/promtool check config %s"
  become_user: root
  become: true
  notify:
    - reload prometheus

- name: create prometheus systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  become_user: root
  become: true
  notify:
    - restart prometheus

- name: ensure prometheus service is started and enabled
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  become_user: root
  become: true
