---
- name: create certificate authority directories on CA
  delegate_to: "{{ nebula_ca }}"
  file:
    path: "{{ nebula_ca_dir }}"
    state: directory

- name: create the organization certificate authority
  delegate_to: "{{ nebula_ca }}"
  command: 'nebula-cert ca -name "{{ nebula_ca_name }}"'
  run_once: true
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates: "{{ nebula_ca_dir }}/ca.crt"

- name: copy ca.crt to nodes
  copy:
    src: "{{ nebula_ca_dir }}/ca.crt"
    dest: "{{ nebula_config_dir }}/ca.crt"
    owner: nebula
    group: nebula
    mode: 0644
  become_user: root
  become: true
  notify:
    - restart nebula

- name: sign certificates for nebula nodes
  delegate_to: "{{ nebula_ca }}"
  command: "{{ 'nebula-cert sign -name ' + inventory_hostname + ' -ip ' + nebula_ip + nebula_cidr + ' -groups ' + nebula_groups }}"
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates: "{{ nebula_ca_dir }}/{{ inventory_hostname }}.crt"

- name: sign certificates for nebula client devices
  delegate_to: "{{ nebula_ca }}"
  command: "{{ 'nebula-cert sign -name ' + item.nebula_hostname + ' -ip ' + item.nebula_ip + nebula_cidr + ' -groups ' + item.nebula_groups }}"
  args:
    chdir: "{{ nebula_ca_dir }}"
    creates: "{{ nebula_ca_dir }}/{{ item.nebula_hostname }}.crt"
  run_once: true
  loop: "{{ nebula_client_devices }}"

- name: copy cert file to node
  copy:
    src: "{{ nebula_ca_dir }}/{{ item }}"
    dest: "{{ nebula_config_dir }}/{{ item }}"
    owner: nebula
    group: nebula
    mode: 0644
  become_user: root
  become: true
  with_items:
    - "{{ inventory_hostname }}.crt"
    - "{{ inventory_hostname }}.key"
