---

- hosts: bakery

  vars_files:
    - vars.yml

  tasks:
    - name: set host MAC address
      set_fact:
        pi_mac_address: "{{ hostvars[inventory_hostname].ansible_default_ipv4.macaddress }}"

    - name: set hostname and ip based on MAC address
      set_fact:
        pi_hostname: "{{ mac_address_mapping[pi_mac_address].name }}"
        pi_ip_address: "{{ mac_address_mapping[pi_mac_address].ip }}"

    - name: set networking config files
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ item.dest }}"
        mode: 0644
      with_items:
        - { template: hosts.j2, dest: /etc/hosts }
        - { template: hostname.j2, dest: /etc/hostname }
        - { template: resolv.conf.j2, dest: /etc/resolv.conf }
        - { template: dhcpcd.conf.j2, dest: /etc/dhcpcd.conf}
      notify:
        - update hostname
        - delete dhcp leases
      become: true
      become_user: root

  handlers:
    - name: update hostname
      command: "hostname {{ pi_hostname }}"
      become: true
      become_user: root
    
    - name: delete dhcp leases
      file:
        path: /var/lib/dhcp/dhclient.leases
        state: absent
      with_items:
        - /var/lib/dhcp/dhclient.leases
        - /var/lib/dhcpcd5/dhcpcd-eth0.lease
      become: true
      become_user: root
