---
go_app_user: curtaincall
go_app_name: curtaincall

go_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcBaFnCXq1oOkiZh7Ghz9MuT8bmv+kO/5rSJOUTy5ku7Q6rCocyj2vcHjGHrvjVfBLwGi25PAdeJ8AAe14Cmpjgns2mY6+JHO8ZxxBbsS7i9nrhgxSgBgcW9iKlPuzPoRpQPy2LR8Bk0oJ/udWmbxmY2uU44rFJL7QcFLnYevq/9HOMYKf0XYJbPorfsV3xzzPN6rtVYLSHBEWZgLZTZqJXpXwykCRU5354qfbjgw0snb3heInj5da/cs4ZsBRRqjxWJWTqe1ZChXTUlKZltAAlERcXphtHY5LlaO1nFt91v8jvFUSJntxEXFaxz4IjKSqwvoZIb6BA0i7tiHgqSNx neherrig@penguin

go_app_env_vars:
  - name: CC_DB_DSN
    value: prod.db
  - name: CC_DB_DRIVER
    value: sqlite3
  - name: CC_ENV
    value: PROD
